### ISSUE TITLE
Flagging that I've found this variable to be very unreliable for timing

### ISSUE THREAD

**Issue by Sfomalley** [PRiSMA-Study/PRISMA-Public#37]
https://github.com/PRiSMA-Study/PRISMA-Public/blob/e50fb738efbe51ea633bc854902cec39bedfdf8a/PRISMA-Maternal-Constructed-Outcomes/Hemorrhage/Maternal-Hemorrhage.R#L269

Apologies if this if addressed later in the code, are we also considering gestational age at hospital visit date?
I've often found hat "ANC" visits happen after birth, "PNC" visits happen before birth

**Comment by sloisate2** [comment]
Updated to calculate age at hospitalization using date mother presented for treatment OR estimated date mother presented for treatment
