### ISSUE TITLE
concerned that several of PPH_FAORRES_88 are not real interventions

### ISSUE THREAD

**Issue by Sfomalley** [PRiSMA-Study/PRISMA-Public#40]
https://github.com/PRiSMA-Study/PRISMA-Public/blob/e50fb738efbe51ea633bc854902cec39bedfdf8a/PRISMA-Maternal-Constructed-Outcomes/Hemorrhage/Maternal-Hemorrhage.R#L331

Looking at the list under PPH_SPFY_FAORRES , some are "none", "nil" , "massage", etc. even if PPH_FAORRES_88 == 1

I am concerned that these women are mistakenly being marked as PPH or severe PPH

**Comment by sloisate2** [comment]
Great catch. Have updated.
