### ISSUE TITLE
Is any woman with a transfusion automatically considered a hemorrhage case?

### ISSUE THREAD

**Issue by Sfomalley** [PRiSMA-Study/PRISMA-Public#42]
https://github.com/PRiSMA-Study/PRISMA-Public/blob/e50fb738efbe51ea633bc854902cec39bedfdf8a/PRISMA-Maternal-Constructed-Outcomes/Hemorrhage/Maternal-Hemorrhage.R#L263

**Comment by sloisate2** [comment]
Another great catch. Have removed.
