### ISSUE TITLE
If hospital records show ML >1000 are they included in this HEM_PPH_SEV variable?

### ISSUE THREAD

**Issue by Sfomalley** [PRiSMA-Study/PRISMA-Public#43]
https://github.com/PRiSMA-Study/PRISMA-Public/blob/e50fb738efbe51ea633bc854902cec39bedfdf8a/PRISMA-Maternal-Constructed-Outcomes/Hemorrhage/Maternal-Hemorrhage.R#L325

**Comment by sloisate2** [comment]
I will definitely add - so far no data available for this variable
