### ISSUE TITLE
Are we excluding unscheduled ANC visits?

### ISSUE THREAD

**Issue by Sfomalley** [PRiSMA-Study/PRISMA-Public#45]
https://github.com/PRiSMA-Study/PRISMA-Public/blob/e50fb738efbe51ea633bc854902cec39bedfdf8a/PRISMA-Maternal-Constructed-Outcomes/Infection/Maternal-Infection-Variables.R#L166

**Comment by sloisate2** [comment]
Another great question! Unscheduled visits will eventually be added in once we start expanding this outcome from only enrollment
