### ISSUE TITLE
What about repeat unscheduled visits?

### ISSUE THREAD

**Issue by Sfomalley** [PRiSMA-Study/PRISMA-Public#46]
https://github.com/PRiSMA-Study/PRISMA-Public/blob/e50fb738efbe51ea633bc854902cec39bedfdf8a/PRISMA-Maternal-Constructed-Outcomes/Infection/Maternal-Infection-Variables.R#L316

**Comment by sloisate2** [comment]
This can be tricky! What I have done in the past for unscheduled visits (example: infant possible and severe bacterial infection), I like to operate in 2 datasets (scheduled and unscheduled) and then merge at the end. 

For example, if a participant has the following unscheduled visits: 

MNH04: visit type = 13 & visit date = 2024-10-15
MNH04: visit type = 13 & visit date = 2024-10-30
MNH06: visit type = 13 & visit date = 2024-10-15

For scheduled visits, you would merge by site, momid, pregid, visit type; However, for unscheduled, you would merge by  site, momid, pregid, visit type, and visit date. In the example above, the MNH04 and MNH06 that occurred on the same day would merge together. Finally, you can merge these back into the scheduled dateset!
