### ISSUE TITLE
Malaria missing if EITHER MNH04 or MNH06 is missing?

### ISSUE THREAD

**Issue by Sfomalley** [PRiSMA-Study/PRISMA-Public#47]
https://github.com/PRiSMA-Study/PRISMA-Public/blob/e50fb738efbe51ea633bc854902cec39bedfdf8a/PRISMA-Maternal-Constructed-Outcomes/Infection/Maternal-Infection-Variables.R#L345

If a woman is missing only one, she is still considered missing?

**Comment by sloisate2** [comment]
Great catch!
