### ISSUE TITLE
If the diagnosis and measurements at a are missing, are these cases coded as zeroes or missing?

### ISSUE THREAD

**Issue by Sfomalley** [PRiSMA-Study/PRISMA-Public#48]
https://github.com/PRiSMA-Study/PRISMA-Public/blob/e50fb738efbe51ea633bc854902cec39bedfdf8a/PRISMA-Maternal-Constructed-Outcomes/Infection/Maternal-Infection-Variables.R#L434

**Comment by sloisate2** [comment]
These cases would be coded as 0s. To get the missing, you would need to use the _MISSING variables
